### ISSUE TITLE
amazon_app_submission not working

### ISSUE THREAD

**Issue by kiketen** [ugroupmedia/fastlane-plugin-amazon-app-store-submission#13]
I've followed the steps that are written in your guide but I'm getting an error and the build is not submitted.

This is my lane:
![image](https://user-images.githubusercontent.com/26503194/183626808-222e2fca-9612-48f9-bdd1-5df1ac176e56.png)

Error that I'm getting:
/opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-plugin-amazon_app_submission-0.3.0/lib/fastlane/plugin/amazon_app_submission/helper/amazon_app_submission_helper.rb:88:in `get_current_apk_id': \e[31m[!] undefined method `[]' for nil:NilClass (NoMethodError)

        apk_id = firstAPK['id']
                         ^^^^^^\e[0m
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-plugin-amazon_app_submission-0.3.0/lib/fastlane/plugin/amazon_app_submission/actions/amazon_app_submission_action.rb:26:in `run'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:130:in `block in parsing_binding'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/gems/fastlane-2.208.0/bin/fastlane:23:in `<top (required)>'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/bin/fastlane:25:in `load'
        from /opt/homebrew/Cellar/fastlane/2.208.0/libexec/bin/fastlane:25:in `<main>'

**Comment by KyrychenkoOleksandr** [comment]
@kiketen make sure that you [associated Security Profile with the API](https://developer.amazon.com/docs/app-submission-api/auth.html#associate-security-profile-with-the-api)

**Comment by kiketen** [comment]
Yeaaah! It was this exactly! Very good job, I've uploaded my app with your plugin and everything has worked as a charm! 
In my case, it has not been uploaded directly because the release notes were empty, so I had an error there. But of course, minor thing that was solved fast! 
Congratulations for the plugin and thank you :D
